
```{r, message=FALSE, warning=FALSE}
library(pheatmap)
library(tidyverse)
library(qiimer)
library(vegan)
library(ape)
library(usedist)
## Visualization packages
library(pander)
library(kableExtra)
library(pheatbuilder)
library(ggbeeswarm)
library(ggsci)
library(viridis)
library(wesanderson)
library(RColorBrewer)
# stats packages
library(adonisplus)
library(nlme)
library(emmeans) # for lmer post-hoc tests
library(broom.mixed)
```


```{r}
se <- function(x) sd(x)/sqrt(length(x))

logit <- function(x) { log(x / (1-x)) }

p_stars <- function (pvals) {
  cut(pvals, breaks = c(-Inf, 0.001, 0.01, 0.05, Inf), labels = c("***", "**", "*", ""))
}

tidy_lm_posthoc <- function(lmer_test, term_string) {
  form1 <- as.formula(paste("pairwise ~", term_string))
  mod <- anova(lmer_test)
  
  if(class(lmer_test) == "lm") {
    main_tidy <- tidy(mod)
  } else {
    main_tidy <- data.frame(term = rownames(mod), mod, row.names=NULL) %>% 
      rename(df=numDF)
  }
  
  bind_rows(main_tidy,
            data.frame(emmeans(lmer_test, form1, adjust="tukey")$contrasts) %>% rename(term = contrast, std.error=SE)
            ) %>%
    mutate(estimate = estimate * -1) %>%
    select(term, df, estimate, std.error,  p.value) ## can also add statistic and t.ratio columns if needed
}

theme_clean <- function(){ 
    theme_bw() %+replace%    #replace elements we want to change
    theme(
      panel.grid = element_blank(), 
      strip.background = element_blank()
    )
}

theme_clean_pcoa <- function(){ 
    theme_bw() %+replace%    #replace elements we want to change
    theme(
      axis.text=element_blank(),
      axis.ticks=element_blank(),
      panel.grid = element_blank(), 
      aspect.ratio = 1,
      strip.background = element_blank()
    )
}

kable_style <- function(data, col_name=p.value, threshold=0.05) {
  
  row_num <- nrow(data)
  
  ##substitute underscore with escaped underscores and remove na in p.value columns
  data_return <- data %>%
    select_all(~gsub("_", "\\\\_", .)) %>% ##need to escape the escape
    select_all(~gsub("#", "\\\\#", .)) %>% ##need to escape the escape
    mutate_if(function(x) is.character(x) | is.factor(x), ~gsub("_", " ", .)) %>%
    mutate_if(function(x) is.character(x) | is.factor(x), ~gsub("%", "\\\\%", .))
  
  ## highlight significant values
  col_name <- enquo(col_name)
  data_return <- data_return %>%
    mutate(!!col_name := cell_spec(signif(!!col_name, 2), "latex", bold = !!col_name<threshold))
  
  ##if Taxa is a column in the dataframe
  if(sum(grepl("Taxa", colnames(data_return))) > 0)  {
    data_return <- data_return %>%
      mutate(Taxa = gsub("[pcofgs]__", "", Taxa))
  }
  
  # ... should be column number
  if (row_num > 15) {
    data_return <- data_return %>%
      kable("latex", longtable = T, digits=2, booktabs=T, escape=F) %>%
      kable_styling(latex_options = c("repeat_header", "HOLD_position"), font_size = 7) %>%
      row_spec(0, bold = T, color="#7C0A02") #%>%
      #collapse_rows(columns = 1, valign = "top") 
    
  }
  else {
    data_return <- data_return %>%
      kable("latex", longtable = F, digits=2, booktabs=T, escape=F) %>%
      kable_styling(latex_options = c("scale_down", "repeat_header", "HOLD_position")) %>%
      row_spec(0, bold = T, color="#7C0A02")
    
    if(row_num > 1) { ##always collapse row unless there is only 1 row
      data_return <- data_return %>%
        collapse_rows(columns = 1, valign = "top")
    }
  }
  
  return(data_return)
  
}
```



```{r}
### number of samples threshold to show heatmap on the page
data_dir <- "Data"

### mapping file path
mapping_file_fp <- file.path(data_dir, "20211005_calico_metadata_runs12_merged.txt")

### taxonomic assignment 
feature_table_fp <- file.path(data_dir, "20240826_kraken_merged.tsv")

perm <- 999
```

```{r sample_sheet_import, echo=FALSE}
s <- read.delim(mapping_file_fp, sep='\t') %>%
  mutate(SampleID = as.character(SampleID)) %>%
  mutate(SubjectID = as.character(SubjectID)) %>%
  
  mutate(SampleType = fct_rev(SampleType)) %>%
  mutate(SampleType = fct_relevel(SampleType, "Cecal contents", after=0)) %>%
  mutate(SampleType = fct_relevel(SampleType, "Feces", after=0)) %>%
  mutate(sex = fct_rev(sex)) %>%
  mutate(breeding_status = fct_relevel(breeding_status, "Breeder", after=2)) %>%
  
  mutate(age_groups = factor(study_group3, levels=c("1 to 4", "7 to 8", "11 to 13", "17 to 18", "26 to 33"))) %>%
  mutate(age_groups_ordered = factor(age_groups, ordered = T)) %>%
  
  mutate(study_group5 = factor(study_group5, levels=c("Pre", "1d", "14d", "30d", "Untreated"))) %>%
  mutate(study_group5_linear = factor(study_group5, ordered=T)) %>%
  
  mutate(HostSpecies = factor(HostSpecies))


contrasts(s$age_groups) <- matrix(c(-4/5, 1/5, 1/5, 1/5, 1/5,  -3/5, -3/5, 2/5, 2/5, 2/5,  -2/5, -2/5, -2/5, 3/5, 3/5,  -1/5, -1/5, -1/5, -1/5, 4/5), ncol = 4)
```




```{r}
o <- read_qiime_otu_table(feature_table_fp)

# Metadata in the form of truncated green genes assignments
md <- sub("(; [kpcofgs]__)+$", "", o$metadata, perl=T)
md <- gsub("[kpcofgs]__", "", md)  

# Assignments data-frame
adf <- split_assignments(md) #%>%
  #mutate(Species = ifelse(!is.na(Genus) & !is.na(Species), paste(Genus, Species), NA))
a <- simplify_assignments(adf, rank1 = "Phylum", rank2="Species")

cts <- o$counts
colnames(cts) <- sub("\\.taxa$", "", colnames(cts))


is_human <- grepl("Chordata", adf$Phylum)
adf <- adf[!is_human,]
a <- a[!is_human]
cts <- cts[!is_human,]

cts_props <- sweep(cts, 2, colSums(cts), "/")
summed_cts <- rowsum(cts, a) 
summed_props <- sweep(summed_cts, 2, colSums(summed_cts), "/")


a_g <- simplify_assignments(adf, rank1="Phylum", rank2="Genus")
summed_cts_g <- rowsum(cts, a_g) 
summed_props_g <- sweep(summed_cts_g, 2, colSums(summed_cts_g), "/")
#otu_props_g <- sweep(summed_cts_g, 2, colSums(summed_cts_g), "/")


a_p <- simplify_assignments(adf, rank1="Kingdom", rank2="Phylum")
summed_cts_p <- rowsum(cts, a_p) 
summed_props_p <- sweep(summed_cts_p, 2, colSums(summed_cts_p), "/")

s <- merge(s, data.frame(otu_counts= colSums(summed_cts)), by.x="SampleID", by.y="row.names", all.x=T)
```

```{r alpha}
s <- s %>%
  merge(diversity(t(cts)), by.x="SampleID", by.y="row.names", all.x=T) %>%
  dplyr::rename(shannon = y) %>%
  merge(rarefy(t(cts), 1000), by.x="SampleID", by.y="row.names", all.x=T) %>%
  dplyr::rename(richness = y) 
```


```{r beta}
bc <- vegdist(t(summed_props))
jd <- vegdist(t(summed_props), method="jaccard", binary = T)

```

```{r}

ann_colors <- list(
  breeding_status = setNames(brewer.pal(4, "Set1"), levels(s$breeding_status)),
  sex = setNames(brewer.pal(6, "Dark2")[c(1,2)], levels(s$sex)),
  HostSpecies = setNames(brewer.pal(4, "Set2")[c(3,4)], levels(s$HostSpecies)),
  SampleType = setNames(brewer.pal(7, "Paired"), levels(s$SampleType)),
  age_groups = setNames(brewer.pal(9, "YlOrRd")[c(2,4,6,8,9)], levels(s$age_groups)),
  study_group5 = setNames(brewer.pal(9, "Blues")[c(2,4,6,8,9)], levels(s$study_group5)),
  toColor = setNames(c(brewer.pal(12, "Paired")[c(5,1,3,9)], brewer.pal(4, "Set1")), levels(interaction(s$breeding_status, s$sex))),
  age_categories = setNames(viridis(4, end=0.8), c("S1", "S2", "S3", "S4")),
  breeding_status_simple = setNames(c("#1B9AAA", "#62AB37", "#1B512D"), c("Non\nbreeder", "Breeder", "Pregnant")),
  study_group6 = setNames(c("#1B512D", "#62AB37"), c("Before\nbirth", "After\nbirth")),
  sample_type = setNames(c("#13505B", "#769FB6"), c("Feces", "Cecal contents"))
)

```



